In [ ]:
pip install -U spacy

In [ ]:
!python -m spacy download en_core_web_md

In [ ]:
spacy.load('en_core_web_md')

In [ ]:
!pip install wordcloud 

In [ ]:
pip install nltk

In [47]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import string # special operations on strings
import spacy # language models

from matplotlib.pyplot import imread
from matplotlib import pyplot as plt
#from wordcloud import WordCloud
%matplotlib inline

In [48]:
nlp=spacy.load('en_core_web_md')

In [49]:
!python -m spacy download en_core_web_sm
nlp = spacy.load('en_core_web_sm')

Defaulting to user installation because normal site-packages is not writeable
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [50]:
book=pd.read_csv("C:\\Users\\Neha Excelr\\DataSets\\apple.txt",error_bad_lines=False)

C:\Users\Neha Excelr\AppData\Local\Temp\ipykernel_22268\186625874.py:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  book=pd.read_csv("C:\\Users\\Neha Excelr\\DataSets\\apple.txt",error_bad_lines=False)
b'Skipping line 6: expected 1 fields, saw 14\n'


In [51]:
book

x
0   It's amazing..... battery last around 10 -12 h...
1   Finally a MacBook possession. Got it in 50k in...
2   Best Laptop under 60k. If you don't want any a...
3   Pros:1. Light weight and super fast response t...
4                                                   "
5   I am very upset about the product as I checked...
6   Reason for 1 star is I ot an defective piece. ...
7   Got the Apple Macbook air on amazon discount s...
8   White line coming on screen in just three mont...
9   Bought this product recently on 5 April, was w...
10  Hi, Think thousand time before buying. One cal...
11  We buy macbook's expecting that it will lasts ...
12  I use this for music production and it works a...
13  Never purchase any Apple products. I bought 3 ...
14  Good purchase of mineBest for programming...On...
15  I bought MacBook air in 2017, it was working f...
16  Bought it on 9th July, stopped working / not t...
17  I bought it last year from Amazon during Sale....
18              All are Gud.. For now..\n            
19  Apple,apple,apple, thats the first thing that ...
20  After using Windows Operating system for the p...
21  MacBook Air is excellent. The build is super s...
22  Very handy laptop, light weight and portable. ...
23  I was apprehensive of buying Apple product fro...
24  I brought this mac air on sep 2017. From past ...
25  Don't want to mention anything for apple MAC b...
26  I have my worst nightmare with the macbook air...
27  Everything about this product seems to be fine...
28  I was looking for an affordable long lasting l...
29  This is the worst  apple product I have ever s...
30  Amazing product..it has quality written all ov...
31  From the very beginning the battery life was h...
32  The rating isn't for Apple's performance. I ex...
33  I preferred this over other good spec windows ...
34  When i received, within 15 days i realised the...
35  Be careful while buying electronic products th...
36  MERITS..IT IS BEST IN ITS PERFORMANCE..SOUND Q...
37  3 years and still running! great product\n    ...
38  The elegant work of apple can be seen in this ...
39  I got a great deal on this laptop, which I hav...

In [52]:
len(book)

40

In [53]:
book = [x.strip() for x in book.x] # remove both the leading and the trailing spaces
book = [x for x in book if x] # removes empty strings, because they are considered in Python as False
book[0:10]            

["It's amazing..... battery last around 10 -12 hrs.....best laptop for students and coders",
 "Finally a MacBook possession. Got it in 50k in Diwali sale. Technically good laptop.Good News.luxury product, niche technology, good battery life, reliable machine (other laptops crash and become defunct in 6-10 years), no anti-virus required, security of data and transactions much better. Terrific sense of possession & pride.Bad News. Problems will be there if you are switching from windows based system - very less space in hard disk, no CD drive, inability to transfer data from Mac to your existing external hard disc unless you format it, apps are mostly paid and re unreasonably expensive (no free apps which are available otherwise on google play store, even the angry bird costs Rs 400 !!), all printers are not compatible (e.g. the most economical MFD laser printer RICOH SP 111 can't be used), huge compatibility issues with Pages (MS Word) and Keynote (powerpoint) unless you master it by wo

In [54]:
# Joining the list into one string/text
text = ' '.join(book)
text

'It\'s amazing..... battery last around 10 -12 hrs.....best laptop for students and coders Finally a MacBook possession. Got it in 50k in Diwali sale. Technically good laptop.Good News.luxury product, niche technology, good battery life, reliable machine (other laptops crash and become defunct in 6-10 years), no anti-virus required, security of data and transactions much better. Terrific sense of possession & pride.Bad News. Problems will be there if you are switching from windows based system - very less space in hard disk, no CD drive, inability to transfer data from Mac to your existing external hard disc unless you format it, apps are mostly paid and re unreasonably expensive (no free apps which are available otherwise on google play store, even the angry bird costs Rs 400 !!), all printers are not compatible (e.g. the most economical MFD laser printer RICOH SP 111 can\'t be used), huge compatibility issues with Pages (MS Word) and Keynote (powerpoint) unless you master it by worki

In [55]:
#Punctuation
no_punc_text = text.translate(str.maketrans('', '', string.punctuation)) 
#with arguments (x, y, z) where 'x' and 'y'
# must be equal-length strings and characters in 'x' are replaced by characters in 'y'. 
#'z' is a string (string.punctuation here)
no_punc_text

'Its amazing battery last around 10 12 hrsbest laptop for students and coders Finally a MacBook possession Got it in 50k in Diwali sale Technically good laptopGood Newsluxury product niche technology good battery life reliable machine other laptops crash and become defunct in 610 years no antivirus required security of data and transactions much better Terrific sense of possession  prideBad News Problems will be there if you are switching from windows based system  very less space in hard disk no CD drive inability to transfer data from Mac to your existing external hard disc unless you format it apps are mostly paid and re unreasonably expensive no free apps which are available otherwise on google play store even the angry bird costs Rs 400  all printers are not compatible eg the most economical MFD laser printer RICOH SP 111 cant be used huge compatibility issues with Pages MS Word and Keynote powerpoint unless you master it by working on these still mostly the document and slides ei

In [56]:
#Alternate code for removing punctuation
#no_punc_text= [word for word in no_punc_text if word.isalnum()]
#no_punc_text

In [57]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\Neha
[nltk_data]     Excelr\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [58]:
#Tokenization
from nltk.tokenize import word_tokenize
text_tokens = word_tokenize(no_punc_text)
print(text_tokens[0:50])

['Its', 'amazing', 'battery', 'last', 'around', '10', '12', 'hrsbest', 'laptop', 'for', 'students', 'and', 'coders', 'Finally', 'a', 'MacBook', 'possession', 'Got', 'it', 'in', '50k', 'in', 'Diwali', 'sale', 'Technically', 'good', 'laptopGood', 'Newsluxury', 'product', 'niche', 'technology', 'good', 'battery', 'life', 'reliable', 'machine', 'other', 'laptops', 'crash', 'and', 'become', 'defunct', 'in', '610', 'years', 'no', 'antivirus', 'required', 'security', 'of']


In [59]:
len(text_tokens)

3444

In [60]:
#Normalize the data
lower_words = [x.lower() for x in text_tokens]
print(lower_words[0:25])

['its', 'amazing', 'battery', 'last', 'around', '10', '12', 'hrsbest', 'laptop', 'for', 'students', 'and', 'coders', 'finally', 'a', 'macbook', 'possession', 'got', 'it', 'in', '50k', 'in', 'diwali', 'sale', 'technically']


In [61]:
#Remove stopwords
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Neha
[nltk_data]     Excelr\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [62]:
my_stop_words = stopwords.words('english')
my_stop_words

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [63]:
my_stop_words.append('the')
no_stop_tokens = [word for word in lower_words if not word in my_stop_words]
print(no_stop_tokens[0:40])

['amazing', 'battery', 'last', 'around', '10', '12', 'hrsbest', 'laptop', 'students', 'coders', 'finally', 'macbook', 'possession', 'got', '50k', 'diwali', 'sale', 'technically', 'good', 'laptopgood', 'newsluxury', 'product', 'niche', 'technology', 'good', 'battery', 'life', 'reliable', 'machine', 'laptops', 'crash', 'become', 'defunct', '610', 'years', 'antivirus', 'required', 'security', 'data', 'transactions']


In [64]:
len(no_stop_tokens)

1905

In [65]:
len(lower_words)

3444

In [66]:
#Stemming
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [67]:
stemmed_tokens = [ps.stem(word) for word in no_stop_tokens]
print(stemmed_tokens[0:40])

['amaz', 'batteri', 'last', 'around', '10', '12', 'hrsbest', 'laptop', 'student', 'coder', 'final', 'macbook', 'possess', 'got', '50k', 'diwali', 'sale', 'technic', 'good', 'laptopgood', 'newsluxuri', 'product', 'nich', 'technolog', 'good', 'batteri', 'life', 'reliabl', 'machin', 'laptop', 'crash', 'becom', 'defunct', '610', 'year', 'antiviru', 'requir', 'secur', 'data', 'transact']


In [68]:
for w in no_stop_tokens:
    print(w, " : ", ps.stem(w))

amazing  :  amaz
battery  :  batteri
last  :  last
around  :  around
10  :  10
12  :  12
hrsbest  :  hrsbest
laptop  :  laptop
students  :  student
coders  :  coder
finally  :  final
macbook  :  macbook
possession  :  possess
got  :  got
50k  :  50k
diwali  :  diwali
sale  :  sale
technically  :  technic
good  :  good
laptopgood  :  laptopgood
newsluxury  :  newsluxuri
product  :  product
niche  :  nich
technology  :  technolog
good  :  good
battery  :  batteri
life  :  life
reliable  :  reliabl
machine  :  machin
laptops  :  laptop
crash  :  crash
become  :  becom
defunct  :  defunct
610  :  610
years  :  year
antivirus  :  antiviru
required  :  requir
security  :  secur
data  :  data
transactions  :  transact
much  :  much
better  :  better
terrific  :  terrif
sense  :  sens
possession  :  possess
pridebad  :  pridebad
news  :  news
problems  :  problem
switching  :  switch
windows  :  window
based  :  base
system  :  system
less  :  less
space  :  space
hard  :  hard
disk  :  disk
c

part  :  part
week  :  week
warranty  :  warranti
expiration  :  expir
date  :  date
buy  :  buy
macbooks  :  macbook
expecting  :  expect
lasts  :  last
least  :  least
3  :  3
years  :  year
case  :  case
saying  :  say
costs  :  cost
46000rs  :  46000r
repair  :  repair
bought  :  bought
58000rs  :  58000r
dont  :  dont
want  :  want
repair  :  repair
still  :  still
ive  :  ive
pay  :  pay
2500rs  :  2500r
diagnostic  :  diagnost
cost  :  cost
recommended  :  recommend
use  :  use
music  :  music
production  :  product
works  :  work
awesomehowever  :  awesomehowev
display  :  display
good  :  good
63k  :  63k
laptop  :  laptop
never  :  never
purchase  :  purchas
apple  :  appl
products  :  product
bought  :  bought
3  :  3
start  :  start
giving  :  give
problems  :  problem
6  :  6
months  :  month
need  :  need
visit  :  visit
4  :  4
times  :  time
service  :  servic
station  :  station
far  :  far
12  :  12
km  :  km
macbook  :  macbook
start  :  start
acting  :  act
dead  : 

exporting  :  export
4k60fps  :  4k60fp
video  :  video
cpu  :  cpu
gpu  :  gpu
went  :  went
104  :  104
degrees  :  degre
reason  :  reason
going  :  go
apple  :  appl
support  :  support
thank  :  thank
read  :  read
whole  :  whole
review  :  review
spent  :  spent
lot  :  lot
time  :  time
writing  :  write
thisupdate  :  thisupd
8  :  8
oct  :  oct
2019apple  :  2019appl
service  :  servic
nothing  :  noth
thought  :  thought
service  :  servic
yes  :  ye
changed  :  chang
thermal  :  thermal
paste  :  past
dusted  :  dust
fan  :  fan
everything  :  everyth
running  :  run
even  :  even
better  :  better
ever  :  ever
even  :  even
heating  :  heat
issua  :  issua
solved  :  solv
exporting  :  export
4k  :  4k
60  :  60
fps  :  fp
video  :  video
around  :  around
80  :  80
degrees  :  degre
hence  :  henc
thermal  :  thermal
throttling  :  throttl
yay  :  yay
using  :  use
windows  :  window
operating  :  oper
system  :  system
past  :  past
10  :  10
years  :  year
switched  : 

arenot  :  arenot
productive  :  product
person  :  person
play  :  play
gamesandtheres  :  gamesandther
nothing  :  noth
much  :  much
bad  :  bad
3  :  3
years  :  year
still  :  still
running  :  run
great  :  great
product  :  product
elegant  :  eleg
work  :  work
apple  :  appl
seen  :  seen
product  :  product
design  :  design
user  :  user
friendliness  :  friendli
compactness  :  compact
easily  :  easili
seen  :  seen
laptop  :  laptop
coming  :  come
performance  :  perform
speed  :  speed
remarkable  :  remark
get  :  get
know  :  know
power  :  power
mac  :  mac
os  :  os
another  :  anoth
apple  :  appl
product  :  product
get  :  get
one  :  one
best  :  best
movie  :  movi
experiences  :  experi
overall  :  overal
would  :  would
455  :  455
got  :  got
great  :  great
deal  :  deal
laptop  :  laptop
using  :  use
almost  :  almost
year  :  year
got  :  got
discount  :  discount
also  :  also
able  :  abl
exchange  :  exchang
old  :  old
laptop  :  laptop
laptop  :  la

In [69]:
# NLP english language model of spacy library

In [70]:
# lemmas being one of them, but mostly POS, which will follow later
doc = nlp(' '.join(stemmed_tokens))
print(doc[0:40])

amaz batteri last around 10 12 hrsbest laptop student coder final macbook possess got 50k diwali sale technic good laptopgood newsluxuri product nich technolog good batteri life reliabl machin laptop crash becom defunct 610 year antiviru requir secur data transact


In [71]:
lemmas = [token.lemma_ for token in doc]
print(lemmas[0:25])

['amaz', 'batteri', 'last', 'around', '10', '12', 'hrsb', 'laptop', 'student', 'coder', 'final', 'macbook', 'possess', 'get', '50k', 'diwali', 'sale', 'technic', 'good', 'laptopgood', 'newsluxuri', 'product', 'nich', 'technolog', 'good']


In [72]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to C:\Users\Neha
[nltk_data]     Excelr\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [73]:
for w in lower_words:
    print(w, " : ", lemmatizer.lemmatize(w))

LookupError: 
**********************************************************************
  Resource omw-1.4 not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('omw-1.4')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/omw-1.4

  Searched in:
    - 'C:\\Users\\Neha Excelr/nltk_data'
    - 'C:\\ProgramData\\Anaconda3\\nltk_data'
    - 'C:\\ProgramData\\Anaconda3\\share\\nltk_data'
    - 'C:\\ProgramData\\Anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\Neha Excelr\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************


In [74]:
from nltk.corpus import wordnet as wn
from nltk.stem.wordnet import WordNetLemmatizer
from nltk import word_tokenize, pos_tag
from collections import defaultdict
tag_map = defaultdict(lambda : wn.NOUN)
#tag_map['J'] = wn.ADJ
#tag_map['V'] = wn.VERB
#tag_map['R'] = wn.ADV

In [75]:
for token, tag in pos_tag(lower_words):
    lemma = lemma_function.lemmatize(token, tag_map[tag[0]])
    print(token, "=>", lemma)

LookupError: 
**********************************************************************
  Resource averaged_perceptron_tagger not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load taggers/averaged_perceptron_tagger/averaged_perceptron_tagger.pickle

  Searched in:
    - 'C:\\Users\\Neha Excelr/nltk_data'
    - 'C:\\ProgramData\\Anaconda3\\nltk_data'
    - 'C:\\ProgramData\\Anaconda3\\share\\nltk_data'
    - 'C:\\ProgramData\\Anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\Neha Excelr\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************


#### Feature Extraction

In [76]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(stemmed_tokens)

In [77]:
print(vectorizer.vocabulary_)

{'amaz': 68, 'batteri': 115, 'last': 438, 'around': 91, '10': 0, '12': 6, 'hrsbest': 375, 'laptop': 431, 'student': 732, 'coder': 175, 'final': 307, 'macbook': 469, 'possess': 586, 'got': 342, '50k': 36, 'diwali': 238, 'sale': 653, 'technic': 748, 'good': 339, 'laptopgood': 434, 'newsluxuri': 522, 'product': 603, 'nich': 524, 'technolog': 749, 'life': 447, 'reliabl': 631, 'machin': 471, 'crash': 199, 'becom': 118, 'defunct': 219, '610': 46, 'year': 844, 'antiviru': 78, 'requir': 638, 'secur': 667, 'data': 210, 'transact': 784, 'much': 513, 'better': 123, 'terrif': 753, 'sens': 672, 'pridebad': 596, 'news': 521, 'problem': 600, 'switch': 741, 'window': 825, 'base': 113, 'system': 742, 'less': 444, 'space': 706, 'hard': 355, 'disk': 233, 'cd': 161, 'drive': 244, 'inabl': 388, 'transfer': 785, 'mac': 468, 'exist': 279, 'extern': 290, 'disc': 231, 'unless': 792, 'format': 317, 'app': 81, 'mostli': 507, 'paid': 560, 'unreason': 793, 'expens': 281, 'free': 320, 'avail': 99, 'otherwis': 553, 

In [78]:
print(vectorizer.get_feature_names()[1:20])
print(X.toarray()[0:50])

['104', '10day', '11', '111', '1112', '12', '12000', '128', '128gb', '13000', '133', '15', '16', '200', '2013', '2017', '2018', '2019', '2019appl']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [79]:
print(X.toarray().shape)

(1905, 848)


In [80]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

#### Let's see how can bigrams and trigrams can be included here

In [81]:
vectorizer_ngram_range = CountVectorizer(analyzer='word',ngram_range=(1,4),
                                         max_features = 100)
bow_matrix_ngram =vectorizer_ngram_range.fit_transform(book)

In [46]:
print(vectorizer_ngram_range.get_feature_names())
print(bow_matrix_ngram.toarray())

['about', 'after', 'air', 'all', 'am', 'amazon', 'an', 'and', 'any', 'apple', 'are', 'around', 'as', 'at', 'bad', 'battery', 'be', 'best', 'better', 'bought', 'but', 'buy', 'can', 'can be', 'center', 'cost', 'display', 'even', 'fine', 'for', 'from', 'get', 'good', 'got', 'great', 'hard', 'has', 'have', 'if', 'if you', 'if you are', 'in', 'is', 'is not', 'it', 'it is', 'its', 'just', 'keyboard', 'laptop', 'like', 'mac', 'macbook', 'macbook air', 'me', 'months', 'my', 'need', 'no', 'not', 'now', 'of', 'of the', 'on', 'on this', 'one', 'only', 'or', 'other', 'product', 'quality', 'sale', 'screen', 'service', 'so', 'stopped', 'that', 'the', 'then', 'there', 'they', 'this', 'to', 'using', 'very', 'want', 'want to', 'warranty', 'was', 'which', 'while', 'will', 'windows', 'with', 'working', 'would', 'year', 'years', 'you', 'you are']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 8 1]
 [1 0 0 ... 0 7 1]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 0 0 0]]


#### TFidf vectorizer

In [82]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [84]:
tfidf_vectorizer = TfidfVectorizer(norm="l2",analyzer='word', 
                                                 ngram_range=(1,3), 
                                                 max_features = 500)

In [85]:
tf_idf_matrix =tfidf_vectorizer.fit_transform(book)

In [87]:
print(tfidf_vectorizer.get_feature_names())
print(tf_idf_matrix.toarray())

['10', '12', '2017', '4k', '50k', 'about', 'about the', 'above', 'after', 'after using', 'again', 'air', 'all', 'also', 'am', 'amazing', 'amazon', 'an', 'and', 'and after', 'and is', 'and it', 'and the', 'and then', 'any', 'apple', 'apple product', 'apple service', 'apple support', 'apps', 'apps which', 'apps which are', 'april', 'are', 'are really', 'are way', 'around', 'as', 'as it', 'asked', 'asked for', 'at', 'at all', 'at the', 'at the price', 'automatically', 'available', 'awesome', 'back', 'backup', 'bad', 'battery', 'battery life', 'be', 'be fine', 'be ignored', 'be it', 'be it the', 'be used', 'because', 'been', 'being', 'best', 'best laptop', 'best laptop for', 'better', 'better graphics', 'better than', 'bit', 'board', 'book', 'both', 'bought', 'bought it', 'bought it on', 'bought this', 'bought this macbook', 'box', 'build', 'but', 'but can', 'but can be', 'but if', 'but if you', 'butter', 'button', 'buy', 'buying', 'by', 'can', 'can be', 'can be ignored', 'can get', 'canno

####  Generate wordcloud

In [ ]:
# Import packages
import matplotlib.pyplot as plt
%matplotlib inline
from wordcloud import WordCloud, STOPWORDS

In [ ]:
# Define a function to plot word cloud
def plot_cloud(wordcloud):
    # Set figure size
    plt.figure(figsize=(40, 30))
    # Display image
    plt.imshow(wordcloud) 
    # No axis details
    plt.axis("off");

In [ ]:
# Generate wordcloud
stopwords = STOPWORDS
stopwords.add('will')
stopwords.add('apple')
stopwords.add('Amazon')
stopwords.add('laptop')



wordcloud = WordCloud(width = 3000, height = 2000, background_color='black', max_words=100,
                      colormap='Set2',stopwords=stopwords).generate(text)
# Plot
plot_cloud(wordcloud)

In [ ]:
wordcloud = WordCloud(width = 2000, height = 2000, background_color='black', max_words=60,
                      colormap='Set2',stopwords=stopwords).generate(text)
# Plot
plot_cloud(wordcloud)

In [ ]:
# Save image
#wordcloud.to_file("wordcloud.png")